version: "3"

services:
  opensea_downloader:
    image: makevoid/opensea_images_downloader
    build:
      context: .
      args:
        COLLECTION_NAME: "$COLLECTION_NAME"
    volumes:
      - ./output:/app/output
